// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentControl.Infrastructure;

#nullable disable

namespace StudentControl.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221204170131_MySqlMigration")]
    partial class MySqlMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OrderStudent", b =>
                {
                    b.Property<string>("ordersId")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("studentsid")
                        .HasColumnType("char(36)");

                    b.HasKey("ordersId", "studentsid");

                    b.HasIndex("studentsid");

                    b.ToTable("OrderStudent");
                });

            modelBuilder.Entity("StudentControl.Domain.Model.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("StudyProfile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("formofstudy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("StudentControl.Domain.Model.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("StudentControl.Domain.Model.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StudentControl.Domain.Model.Student", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<short>("graduate")
                        .HasColumnType("smallint");

                    b.Property<Guid>("groupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("loginId")
                        .HasColumnType("char(36)");

                    b.Property<string>("middle_name")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("snils")
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("groupId");

                    b.HasIndex("loginId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("OrderStudent", b =>
                {
                    b.HasOne("StudentControl.Domain.Model.Order", null)
                        .WithMany()
                        .HasForeignKey("ordersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentControl.Domain.Model.Student", null)
                        .WithMany()
                        .HasForeignKey("studentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentControl.Domain.Model.Student", b =>
                {
                    b.HasOne("StudentControl.Domain.Model.Group", "group")
                        .WithMany("students")
                        .HasForeignKey("groupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentControl.Domain.Model.Login", "login")
                        .WithMany()
                        .HasForeignKey("loginId");

                    b.Navigation("group");

                    b.Navigation("login");
                });

            modelBuilder.Entity("StudentControl.Domain.Model.Group", b =>
                {
                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
